
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cda611
 */
public class primoJif extends javax.swing.JInternalFrame {

    /**
     * Creates new form primoJif
     */
    public primoJif() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        livMenu = new javax.swing.JMenu();
        cl1Menu = new javax.swing.JMenuItem();
        aut1Menu = new javax.swing.JMenuItem();
        liv1Menu = new javax.swing.JMenuItem();
        modifMenu = new javax.swing.JMenu();
        clmoMenu = new javax.swing.JMenuItem();
        autMoMenu = new javax.swing.JMenuItem();
        livMoMenu = new javax.swing.JMenuItem();
        prixMoMenu = new javax.swing.JMenuItem();
        searchMenu = new javax.swing.JMenu();
        commaMenu = new javax.swing.JMenu();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        livMenu.setText("Création");
        livMenu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                livMenuStateChanged(evt);
            }
        });
        livMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livMenuActionPerformed(evt);
            }
        });

        cl1Menu.setText("Client");
        cl1Menu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cl1MenuStateChanged(evt);
            }
        });
        cl1Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cl1MenuActionPerformed(evt);
            }
        });
        livMenu.add(cl1Menu);

        aut1Menu.setText("Auteur");
        livMenu.add(aut1Menu);

        liv1Menu.setText("Ouvrage");
        liv1Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liv1MenuActionPerformed(evt);
            }
        });
        livMenu.add(liv1Menu);

        jMenuBar1.add(livMenu);

        modifMenu.setText("Modification");

        clmoMenu.setText("Client");
        clmoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clmoMenuActionPerformed(evt);
            }
        });
        modifMenu.add(clmoMenu);

        autMoMenu.setText("Auteur");
        modifMenu.add(autMoMenu);

        livMoMenu.setText("Ouvrage");
        modifMenu.add(livMoMenu);

        prixMoMenu.setText("Prix");
        modifMenu.add(prixMoMenu);

        jMenuBar1.add(modifMenu);

        searchMenu.setText("Recherche");
        searchMenu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                searchMenuStateChanged(evt);
            }
        });
        searchMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(searchMenu);

        commaMenu.setText("Gestion commande");
        jMenuBar1.add(commaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMenuActionPerformed
        // TODO add your handling code here:
      JFrame f1 = new JFrame();
      System.out.println("Test ");
      f1.setBounds(540, 540, 870, 540);
      f1.add(new researchJPanel());
      f1.setVisible(true);
     System.out.println("Test ");
        
    }//GEN-LAST:event_searchMenuActionPerformed

    private void clmoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clmoMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clmoMenuActionPerformed

    private void liv1MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liv1MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_liv1MenuActionPerformed

    private void livMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livMenuActionPerformed
        // TODO add your handling code here:
     

        
    }//GEN-LAST:event_livMenuActionPerformed

    private void cl1MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl1MenuActionPerformed
      clientJPanel cp = new clientJPanel();
           cp.setVisible(true);
           cp.setSize(240, 240);
        this.getContentPane().add(cp);
          
         System.out.println("Test ");
               
    }//GEN-LAST:event_cl1MenuActionPerformed

    private void searchMenuStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_searchMenuStateChanged
        // TODO add your handling code here:
      JFrame f1 = new JFrame();
      System.out.println("Test ");
      f1.setBounds(540, 540, 870, 540);
      f1.add(new researchJPanel());
      f1.setVisible(true);
      
       pack();
     System.out.println("Test ");
    }//GEN-LAST:event_searchMenuStateChanged

    private void livMenuStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_livMenuStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_livMenuStateChanged

    private void cl1MenuStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cl1MenuStateChanged
        // TODO add your handling code here:
         
    }//GEN-LAST:event_cl1MenuStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aut1Menu;
    private javax.swing.JMenuItem autMoMenu;
    private javax.swing.JMenuItem cl1Menu;
    private javax.swing.JMenuItem clmoMenu;
    private javax.swing.JMenu commaMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem liv1Menu;
    private javax.swing.JMenu livMenu;
    private javax.swing.JMenuItem livMoMenu;
    private javax.swing.JMenu modifMenu;
    private javax.swing.JMenuItem prixMoMenu;
    private javax.swing.JMenu searchMenu;
    // End of variables declaration//GEN-END:variables
 private javax.swing.JPanel container;
}
